### ISSUE TITLE
a question about the dim of softmax

### ISSUE THREAD

**Issue by ericsqxd** [pppLang/SKNet#1]
The shape of the attention_vector is [8, 2, 64], we need to softmax for the channel. So, I think the 
dim of 
                  self.softmax = nn.Softmax(dim=1)
is dim=2. Is it right? thank you!

**Comment by ericsqxd** [comment]
I had just read the paper and I found I'm wrong. Thank you!

**Comment by pppLang** [comment]
Oh, sorry, I saw it so late~  anyway, welcome to ask any questions about the implement code~
