### ISSUE TITLE
I re-implemented SKNET using PyTorch!

### ISSUE THREAD

**Issue by developer0hye** [pppLang/SKNet#11]
Thank you for sharing great works!

I can understand the details for the implementation of Selective Convolution because of this project!

But I found the implementation in this project are different from the original paper(Selective Kernel Networks), so I re-implemented SKNET through your project.

If someone is interested in other implementation of SKNET, refer to [my project](https://github.com/developer0hye/SKNet-PyTorch)!

I tried to implement SKNET using PyTorch equals the original implementation described in the paper.

**Comment by yoookoo** [comment]
So what's the difference?

**Comment by developer0hye** [comment]
@yoookoo 
more readable
